name: Deploy To Okteto

on:
  push:
    branches:
      - master



jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: test

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: sha-${{ github.sha }}
        timeout: 8m
        skipIfExists: false
        variables: "DB_HOST=mysql,CONFIG_PATH=/tmp/config.yaml"
